name: Resettable-Arenas
version: ${project.version}
main: com.github.thedeathlycow.resettablearenas.ResettableArenas
api-version: 1.17
authors: [TheDeathlyCow]
description: Allows arenas to be reset.
depend: [WorldEdit]


commands:
  arena:
    description: Define, save, and load arenas.
    usage: /arena <help | define | list | save | load> <params>
    permission: arenas.permission
    permission-message: ยง3ResettableArenas ยงf- You do not have permission to do that.