name: Resettable-Arenas
version: ${project.version}
main: com.github.thedeathlycow.resettablearenas.ResettableArenas
api-version: 1.17
authors: [TheDeathlyCow]
description: Allows arenas to be reset.
depend: [WorldEdit]

chunk-size: 16

commands:
  arena:
    description: Reload or list arenas.
    usage: /arena <reload | list>
    permission: arenas.permission
    permission-message: ยง3ResettableArenas ยงf- You do not have permission to do that.